version: 2
jobs:

  build_python34:
    docker:
    - image: circleci/python:3.4
    steps: &steps
    - checkout
    - run: python3 -m venv ~/venv
    - run: ~/venv/bin/pip install -U pip wheel
    - run: ~/venv/bin/pip install .
    # check that --help works
    - run: cd / && ~/venv/bin/upload_to_s3 --help

  build_python35:
    docker:
    - image: circleci/python:3.5
    steps: *steps

  build_python36:
    docker:
    - image: circleci/python:3.6
    steps: *steps

  build_python37:
    docker:
    - image: circleci/python:3.7
    steps: *steps

workflows:
  version: 2
  build_and_test:
    jobs:
    - build_python34
    - build_python35
    - build_python36
    - build_python37
